<?php
//Modules/Installer\Backend\Views\Details.html
_t('Info');
_t('List Modules');
_t('Package Information');
_t('Module Name');
_t('Module Version');
_t('Module Build Date');
_t('Module Description');
_t('Navigation');
_t('Execute');
//Modules/Installer\Backend\Views\List.html
_t('Information');
_t('Upload Modules');
_t('Zip File');
_t('Execute');
_t('List modules');
_t('Module');
_t('Vesion');
_t('Build Date');
_t('State');
_t('Actions');
_t('checked');
_t('Install');
_t('Exclamation');
_t('Lastversion');
_t('Update');
_t('Install');
_t('Bpm');
_t('Backup Module');
_t('Banner Module');
_t('Cashu');
_t('Advanced Content Management System');
_t('Comment Module');
_t('Customer Relationship Management');
_t('Default Module');
_t('Doc');
_t('Packages Installer Module');
_t('Invoice Module');
_t('NewsLetter Module');
_t('Payment Management Module');
_t('Paypal');
_t('Inventory Module');
_t('Sales Order Management Module');
_t('Settings Module');
_t('Backend User Management System');
_t('Webmail Module');
//Modules/Installer/Backend/Views/Details.html
_t('Info');
_t('List Modules');
_t('Package Information');
_t('Module Name');
_t('Module Version');
_t('Module Build Date');
_t('Module Description');
_t('Navigation');
_t('Execute');
//Modules/Installer/Backend/Views/List.html
_t('Information');
_t('Upload Modules');
_t('Zip File');
_t('Execute');
_t('List modules');
_t('Module');
_t('Vesion');
_t('Build Date');
_t('State');
_t('Actions');
_t('checked');
_t('Install');
_t('Exclamation');
_t('Lastversion');
_t('Update');
_t('Install');

